spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/product_db
server.port=8082
# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

spring.cloud.openfeign.enabled=true

# Config Server
spring.config.import=optional:configserver:http://localhost:8888


# Feign + Resilience4j
spring.cloud.openfeign.circuitbreaker.enabled=true

# Configuration Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.auto-create=true
spring.kafka.admin.properties.replication.factor=1

# --- CONSUMER ---
# Utilise un group-id différent de celui du producer si tu en avais un
spring.kafka.producer.group-id=product-group
spring.kafka.producer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Très important pour la désérialisation JSON !
# Fait confiance au package où se trouve ton DTO d'événement.
spring.kafka.producer.properties.spring.json.trusted.packages=com.example.product.dto

# --- PRODUCER ---
kafka.topic.product.created=product.created
kafka.topic.product.updated=product.updated
kafka.topic.product.deleted=product.deleted